spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888
#    The optional: prefix means: if the Config Server is down, your app will still start with local configs instead of failing.




