const app = document.querySelector('#app');
const session = { token: sessionStorage.getItem('fitflow-token'), user: JSON.parse(sessionStorage.getItem('fitflow-user') || 'null') };
const routes = ['dashboard', 'activity', 'recommendations', 'profile'];
const typeIcons = { RUNNING:'🏃', WALKING:'🚶', CYCLING:'🚴', SWIMMING:'🏊', WEIGHT_TRAINING:'🏋️', YOGA:'🧘', HIIT:'⚡', CARDIO:'❤️', STRETCHING:'🤸', OTHER:'✨' };

function esc(value='') { const element=document.createElement('span'); element.textContent=value; return element.innerHTML; }
function saveSession(data) { session.token=data.accessToken; session.user=data.user; sessionStorage.setItem('fitflow-token',data.accessToken); sessionStorage.setItem('fitflow-user',JSON.stringify(data.user)); }
function clearSession() { session.token=null; session.user=null; sessionStorage.clear(); location.hash='#login'; }
async function api(path, options={}) { const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(session.token?{Authorization:`Bearer ${session.token}`}:{}) ,...(options.headers||{})}}); if(response.status===204)return null; const data=await response.json(); if(response.status===401){clearSession();throw new Error('Your session expired. Please sign in again.');}if(!response.ok)throw new Error(data.error||'Request failed');return data; }
function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),2800)}
function authPage(mode='login'){app.innerHTML=`<main class="auth"><section class="auth-card"><div class="logo"><span class="logo-mark">♥</span>FitFlow</div><h1>${mode==='login'?'Welcome back':'Start your fitness journey'}</h1><p class="muted">${mode==='login'?'Sign in to track workouts and receive AI-guided advice.':'Create a secure account. Your password is hashed and never returned to the app.'}</p><form class="form" id="auth-form">${mode==='register'?'<label>First name<input name="firstName" autocomplete="given-name" required></label><label>Last name <input name="lastName" autocomplete="family-name"></label>':''}<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="8" required></label><p id="form-message" class="error hidden"></p><button class="primary" type="submit">${mode==='login'?'Sign in':'Create account'}</button></form><p class="muted">${mode==='login'?'New to FitFlow?':'Already have an account?'} <button class="text-button" id="switch-auth">${mode==='login'?'Create an account':'Sign in'}</button></p></section></main>`;document.querySelector('#switch-auth').onclick=()=>authPage(mode==='login'?'register':'login');document.querySelector('#auth-form').onsubmit=async(e)=>{e.preventDefault();const button=e.submitter;const message=document.querySelector('#form-message');button.disabled=true;try{const fields=Object.fromEntries(new FormData(e.currentTarget));const data=await api(`/api/auth/${mode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(fields)});saveSession(data);location.hash='#dashboard';}catch(error){message.textContent=error.message;message.classList.remove('hidden');button.disabled=false;}}}
function layout(content, page){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="logo"><span class="logo-mark">♥</span>FitFlow</div><nav class="nav">${routes.map(route=>`<button data-route="${route}" class="${page===route?'active':''}">${({dashboard:'▦ Dashboard',activity:'＋ Log activity',recommendations:'✦ Recommendations',profile:'◉ Profile'})[route]}</button>`).join('')}</nav><button class="text-button signout" id="signout">Sign out</button></aside><main class="main">${content}</main></div>`;document.querySelectorAll('[data-route]').forEach(button=>button.onclick=()=>location.hash='#'+button.dataset.route);document.querySelector('#signout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{clearSession()}}}
const heading=(title,subtitle)=>`<div class="top"><div><h1>${title}</h1><p class="muted">${subtitle}</p></div><div class="avatar">${esc(session.user.firstName?.[0]||'U')}</div></div>`;
async function dashboard(){layout(heading(`Good day, ${esc(session.user.firstName)}`,'Your movement, progress, and coaching in one place.')+'<p class="muted">Loading your dashboard…</p>','dashboard');try{const [{activities},{recommendations}]=await Promise.all([api('/api/activities'),api('/api/recommendations')]);const minutes=activities.reduce((sum,x)=>sum+x.duration,0),calories=activities.reduce((sum,x)=>sum+x.caloriesBurned,0);layout(heading(`Good day, ${esc(session.user.firstName)}`,'Your movement, progress, and coaching in one place.')+`<div class="grid metrics"><section class="card metric"><small>Active minutes</small><strong>${minutes}</strong><span class="muted">all recorded sessions</span></section><section class="card metric"><small>Calories burned</small><strong>${calories.toLocaleString()}</strong><span class="muted">estimated from activity</span></section><section class="card metric"><small>Activities</small><strong>${activities.length}</strong><span class="muted">training entries</span></section></div><div class="grid two-column"><section class="card"><h2>Recent activity</h2>${activities.length?activities.slice(0,4).map(activityRow).join(''):'<div class="empty">No activities yet. Log your first session to start tracking.</div>'}</section><section class="card"><h2>Latest AI insight</h2>${recommendations[0]?`<div class="insight"><b>${esc(recommendations[0].summary)}</b><p>${esc(recommendations[0].suggestions[0])}</p></div><button class="text-button" data-go="recommendations">See all advice →</button>`:'<div class="empty">Your personal recommendations will appear after you log an activity.</div>'}</section></div>`,'dashboard');document.querySelector('[data-go]')?.addEventListener('click',()=>location.hash='#recommendations');}catch(error){layout(heading('Dashboard unavailable',error.message),'dashboard')}}
function activityRow(activity){return `<div class="activity-row"><div class="activity-icon">${typeIcons[activity.type]||'✨'}</div><div><b>${esc(activity.type.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase()))}</b><p>${new Date(activity.startTime).toLocaleString()} · ${activity.duration} min</p></div><strong>${activity.caloriesBurned} kcal</strong></div>`}
function activityPage(){layout(heading('Log an activity','Record a completed session. Your personalized recommendation is generated immediately.')+`<section class="card"><form class="form-grid" id="activity-form"><label>Activity type<select name="type">${Object.keys(typeIcons).map(type=>`<option>${type}</option>`).join('')}</select></label><label>Start time<input name="startTime" type="datetime-local" required></label><label>Duration (minutes)<input name="duration" type="number" min="1" max="1440" required></label><label>Calories burned<input name="caloriesBurned" type="number" min="0" max="20000" required></label><label class="wide">Optional notes / metrics<textarea name="notes" rows="3" placeholder="Example: 5 km, average heart rate 138 bpm"></textarea></label><p id="activity-message" class="error hidden wide"></p><div class="wide"><button class="primary" type="submit">Save activity</button></div></form></section>`,'activity');const form=document.querySelector('#activity-form');form.startTime.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);form.onsubmit=async(e)=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const message=document.querySelector('#activity-message');try{await api('/api/activities',{method:'POST',body:JSON.stringify({type:data.type,duration:Number(data.duration),caloriesBurned:Number(data.caloriesBurned),startTime:new Date(data.startTime).toISOString(),additionalMetrics:data.notes?{notes:data.notes}:{}})});toast('Activity saved — AI coaching is ready.');location.hash='#recommendations';}catch(error){message.textContent=error.message;message.classList.remove('hidden')}}}
async function recommendationsPage(){layout(heading('AI recommendations','Coaching generated from your recorded activity details.')+'<p class="muted">Loading recommendations…</p>','recommendations');try{const {recommendations}=await api('/api/recommendations');layout(heading('AI recommendations','Coaching generated from your recorded activity details.')+`<div class="grid">${recommendations.length?recommendations.map(r=>`<article class="card recommendation"><div><span class="tag">${esc(r.type.replaceAll('_',' '))}</span> <span class="muted">${new Date(r.createdAt).toLocaleDateString()}</span></div><b>${esc(r.summary)}</b><div><strong>Suggestions</strong><ul>${r.suggestions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><strong>Safety</strong><ul>${r.safety.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></article>`).join(''):'<section class="card empty">No recommendations yet. Log an activity and FitFlow will create guidance for it.</section>'}</div>`,'recommendations')}catch(error){layout(heading('Recommendations unavailable',error.message),'recommendations')}}
async function profilePage(){layout(heading('Your profile','Account details and access level.')+'<p class="muted">Loading profile…</p>','profile');try{const {user}=await api('/api/auth/me');layout(heading('Your profile','Account details and access level.')+`<section class="card"><div class="form-grid"><div><label>First name<input disabled value="${esc(user.firstName)}"></label></div><div><label>Last name<input disabled value="${esc(user.lastName||'')}"></label></div><div><label>Email<input disabled value="${esc(user.email)}"></label></div><div><label>Role<input disabled value="${esc(user.role)}"></label></div></div><p class="muted">Credentials are not shown or stored in profile data.</p></section>`,'profile')}catch(error){layout(heading('Profile unavailable',error.message),'profile')}}
async function render(){const page=location.hash.slice(1)||'dashboard';if(!session.token){authPage(page==='register'?'register':'login');return}if(!routes.includes(page)){location.hash='#dashboard';return}if(page==='dashboard')return dashboard();if(page==='activity')return activityPage();if(page==='recommendations')return recommendationsPage();return profilePage()}
window.addEventListener('hashchange',render);render();

