spring:
  application:
    name: eureka


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#      https://app.notion.com/p/Eureka-Server-Configuration-3980f92c139c802cbd51ed7754e30cf3?source=copy_link
#      register-with-eureka: false => tells your application not to register itself with the Eureka Server.
#      fetch-registry: false => tells your application not to pull the registry from Eureka.

server:
  port: 8761

