spring.application.name=fitness-monolith

# Database Configuration

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SpringDoc /v3/api-docs endpoint is enabled by default. To disable it in production,\
#  \ set the property 'springdoc.api-docs.enabled=false'
#
#SpringDoc /swagger-ui.html endpoint is enabled by default. To disable it in production, \
#  set the property 'springdoc.swagger-ui.enabled=false'

